version: "3"
services:
  wls-squad-server-info-discord-bot:
    image: ghcr.io/welovesquad/squad-server-info-discord-bot:${BOT_IMAGE_TAG:-latest}
    container_name: wls-squad-server-info-discord-bot
    restart: unless-stopped
    environment:
      - "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}"
      - "DISCORD_AUTHORIZED_ROLES=${DISCORD_AUTHORIZED_ROLES}"
      - "SQUAD_SERVERS=${SQUAD_SERVERS}"
      - "LOGGING_LEVEL=${LOGGING_LEVEL}"
      - "LOGGING_FORMAT=${LOGGING_FORMAT}"
    networks:
      - bridge-ip163
    volumes:
      - wls-squad-server-info-discord-bot-volume:/home/node/app/settings
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_ADDRESS}"

volumes:
  wls-squad-server-info-discord-bot-volume:

networks:
  bridge-ip163:
    external: true
