version: "3"
services:
  squad-server-info-dc-bot:
    container_name: squad-server-info-dc-bot
    image: ghcr.io/welovesquad/squad-server-info-discord-bot:${BOT_IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}"
      - "DISCORD_AUTHORIZED_ROLES=${DISCORD_AUTHORIZED_ROLES}"
      - "SQUAD_SERVERS=${SQUAD_SERVERS}"
      - "LOGGING_LEVEL=${LOGGING_LEVEL}"
      - "LOGGING_FORMAT=${LOGGING_FORMAT}"
    volumes:
      - squad-server-info-dc-bot-vol:/home/node/app/settings
    networks:
      - proxy
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.18.0.17:12201"

networks:
  proxy:
    external: true

volumes:
  squad-server-info-dc-bot-vol:
