version: "3"
services:
  wls-squad-server-info-discord-bot:
    image: ghcr.io/welovesquad/squad-server-info-discord-bot:${BOT_IMAGE_TAG:-latest}
    container_name: wls-squad-server-info-discord-bot
    restart: unless-stopped
    environment:
      - "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}"
      - "DISCORD_AUTHORIZED_ROLES=${DISCORD_AUTHORIZED_ROLES}"
      - "SQUAD_SERVERS=${SQUAD_SERVERS}"
      - "LOGGING_LEVEL=${LOGGING_LEVEL}"
      - "LOGGING_FORMAT=${LOGGING_FORMAT}"
    volumes:
      - wls-squad-server-info-discord-bot-volume:/home/node/app/settings
    networks:
      traefik-static-wan-ip87:
        ipv4_address: ${TRAEFIK_IPV4_ADDRESS}
      proxy-static:
        ipv4_address: ${SERVER_INFO_BOT_STATIC_IP}
    labels:
      - "networking.default-gateway=${GATEWAY_ADDRESS}"
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_ADDRESS}"

networks:
  traefik-static-wan-ip87:
    external: true
  proxy-static:
    external: true

volumes:
  wls-squad-server-info-discord-bot-volume:
